---
apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8070"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    main: manager
  ports:
  - name: ssh
    protocol: TCP
    port: 22           
    targetPort: 22 
  - name: http
    protocol: TCP
    port: 8070          
    targetPort: 8070