---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  namespace: default
spec:
  clusterIP: None
  selector:
    app: spark
    component: master
  ports:
  - name: port-9093
    port: 7077
    targetPort: 7077
  - name: port-8083
    port: 8083
    targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-loadbalancer
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    app: spark
    component: master
  ports:
  - protocol: TCP
    port: 8083           # Port exposed by the LoadBalancer
    targetPort: 8083
