---
apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    main: manager
  ports:
  - name: ssh
    protocol: TCP
    port: 22           
    targetPort: 22 
  - name: http
    protocol: TCP
    port: 8070          
    targetPort: 8070