apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-controller
  namespace: default
  labels:
    app: spark
    component: ui
spec:
  serviceName: "spark-controller-loadbalancer"
  replicas: 1
  selector:
    matchLabels:
      app: spark
      component: ui
  template:
    metadata:
      labels:
        app: spark
        component: ui
    spec:
      containers:
      - name: spark-controller
        image: bumory1987/sparks:ui
        ports:
        - containerPort: 8889
        env:
        - name: STORAGE
          value: "spark-storage-0.spark-storage-service.default.svc.cluster.local"  
        resources:
          requests:
            memory: "2Gi"
            cpu: "1" 
        securityContext:
          privileged: true  