apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-worker
  labels:
    app: spark
    component: worker
spec:
  serviceName: "spark-worker-service"
  replicas: 1
  selector:
    matchLabels:
      app: spark
      component: worker
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      containers:
      - name: spark-worker
        image: bumory1987/sparks:workerv2
        ports:
        - containerPort: 8090
        env:
        - name: SPARK_MASTER_HOST
          value: "spark-master-0.spark-master-service.default.svc.cluster.local"  
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8083"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8090"
        - name: STORAGE
          value: "spark-storage-0.spark-storage-service.default.svc.cluster.local"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
        securityContext:
          privileged: true  