apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default 
  name: myrole-operator
rules:
- apiGroups: [""]  
  resources: ["pods", "services"]
  verbs: ["create", "delete", "get", "list", "update", "watch"]
- apiGroups: ["apps"]  
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "update", "watch"]