apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mybinding
  namespace: default  
subjects:
- kind: ServiceAccount
  name:  spark-account
  namespace: default  
roleRef:
  kind: Role
  name: myrole-operator
  apiGroup: rbac.authorization.k8s.io