---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  namespace: default
spec:
  clusterIP: None
  selector:
    app: spark
    component: master
  ports:
  - name: port-7077
    port: 7077
    targetPort: 7077
  - name: port-8083
    port: 8083
    targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-external
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: spark
    component: master
  ports:
  - protocol: TCP
    port: 8083           
    targetPort: 8083     
