---
apiVersion: v1
kind: Service
metadata:
  name: spark-controller-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: spark
    component: ui
  ports:
  - protocol: TCP
    port: 8889           
    targetPort: 8889   